
import { Client } from "@/types/client";

// Sample initial clients with updated address format
export const initialClients: Client[] = [
  {
    id: "1",
    companyName: "Acme Corporation",
    street: "123 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: "12345",
    accountManager: "Jane Smith",
    mainContact: "John Doe",
    email: "john.doe@acme.com",
    phone: "(555) 123-4567",
    startDate: "2022-01-15",
    status: "active",
    lastContactDate: "2023-08-15"
  },
  {
    id: "2",
    companyName: "Globex Industries",
    street: "456 Tech Blvd",
    city: "Innovation City",
    state: "NY",
    zipCode: "67890",
    accountManager: "Michael Johnson",
    mainContact: "Sarah Williams",
    email: "sarah@globex.com",
    phone: "(555) 987-6543",
    startDate: "2021-06-22",
    status: "inactive",
    lastContactDate: "2023-05-22"
  },
  {
    id: "3",
    companyName: "Wayne Enterprises",
    street: "1007 Mountain Drive",
    city: "Gotham City",
    state: "NJ",
    zipCode: "10101",
    accountManager: "Bruce Wayne",
    mainContact: "Lucius Fox",
    email: "lucius.fox@wayne.com",
    phone: "(555) 228-6283",
    startDate: "2020-03-30",
    status: "active",
  },
  {
    id: "4",
    companyName: "Stark Industries",
    street: "200 Park Avenue",
    city: "New York",
    state: "NY",
    zipCode: "10166",
    accountManager: "Pepper Potts",
    mainContact: "Tony Stark",
    email: "tony@stark.com",
    phone: "(555) 462-7865",
    startDate: "2019-11-12",
    status: "active",
  },
  {
    id: "5",
    companyName: "Oscorp",
    street: "888 Broadway",
    city: "New York",
    state: "NY",
    zipCode: "10003",
    accountManager: "Harry Osborn",
    mainContact: "Norman Osborn",
    email: "norman@oscorp.com",
    phone: "(555) 672-9090",
    startDate: "2021-02-18",
    status: "active",
  },
  {
    id: "6",
    companyName: "Umbrella Corporation",
    street: "765 Research Pkwy",
    city: "Raccoon City",
    state: "CO",
    zipCode: "80202",
    accountManager: "Albert Wesker",
    mainContact: "William Birkin",
    email: "birkin@umbrella.com",
    phone: "(555) 333-2211",
    startDate: "2018-07-23",
    status: "active",
  },
  {
    id: "7",
    companyName: "Cyberdyne Systems",
    street: "18144 El Camino Real",
    city: "Sunnyvale",
    state: "CA",
    zipCode: "94087",
    accountManager: "Miles Dyson",
    mainContact: "Miles Bennett Dyson",
    email: "dyson@cyberdyne.com",
    phone: "(555) 789-4561",
    startDate: "2020-08-29",
    status: "active",
  },
  {
    id: "8",
    companyName: "Initech",
    street: "4120 Freidrich Lane",
    city: "Austin",
    state: "TX",
    zipCode: "73301",
    accountManager: "Bill Lumbergh",
    mainContact: "Peter Gibbons",
    email: "peter@initech.com",
    phone: "(555) 222-3333",
    startDate: "2022-05-12",
    status: "active",
    website: "initech.com"
  },
  {
    id: "9",
    companyName: "Massive Dynamic",
    street: "555 Broadway",
    city: "New York",
    state: "NY",
    zipCode: "10012",
    accountManager: "Nina Sharp",
    mainContact: "Walter Bishop",
    email: "walter@massivedynamic.com",
    phone: "(555) 444-5555",
    startDate: "2021-11-02",
    status: "active",
    website: "massivedynamic.com"
  },
  {
    id: "10",
    companyName: "Hooli",
    street: "1401 N Shoreline Blvd",
    city: "Mountain View",
    state: "CA",
    zipCode: "94043",
    accountManager: "Gavin Belson",
    mainContact: "Jared Dunn",
    email: "jared@hooli.com",
    phone: "(555) 666-7777",
    startDate: "2022-07-18",
    status: "active",
    website: "hooli.com"
  },
  {
    id: "11",
    companyName: "Pied Piper",
    street: "5230 Newell Road",
    city: "Palo Alto",
    state: "CA",
    zipCode: "94303",
    accountManager: "Monica Hall",
    mainContact: "Richard Hendricks",
    email: "richard@piedpiper.com",
    phone: "(555) 888-9999",
    startDate: "2023-01-05",
    status: "active",
    website: "piedpiper.com"
  },
  {
    id: "12",
    companyName: "Soylent Corp",
    street: "101 Future Avenue",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    accountManager: "Henry Santoro",
    mainContact: "William Simonson",
    email: "william@soylent.com",
    phone: "(555) 000-1111",
    startDate: "2022-09-22",
    status: "active",
    website: "soylent.com"
  }
];
